# Generated by Django 2.2.4 on 2019-08-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='submission_folder',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
