# Generated by Django 2.2.4 on 2021-09-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_auto_20190819_2351"),
    ]

    operations = [
        migrations.CreateModel(
            name="Archive",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("team", models.CharField(max_length=150)),
                ("event_name", models.CharField(blank=True, max_length=500)),
                ("position", models.CharField(max_length=5)),
                ("college_name", models.CharField(max_length=10)),
                ("fest_name", models.CharField(blank=True, max_length=100)),
                ("event_month", models.DateField(blank=True, max_length=20, null=True)),
                ("dateCreated", models.DateTimeField(auto_now_add=True)),
                ("dateUpdated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
