# Generated by Django 2.2.4 on 2019-08-09 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "task_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("task_name", models.CharField(max_length=30)),
                ("submission_deadline", models.DateField(max_length=10)),
                ("difficulty_level", models.CharField(max_length=50)),
                ("difficulty_value", models.CharField(default="Easy", max_length=30)),
                ("task_description", models.TextField()),
                ("total_submissions", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_submitted", models.BooleanField(default=False)),
                ("submission_url", models.TextField(blank=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="portal.Task"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.Profile"
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "task")},
            },
        ),
    ]
