# Generated by Django 2.2.4 on 2019-08-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0005_auto_20190822_2303"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="tag",
            field=models.CharField(max_length=50),
        ),
    ]
