# Generated by Django 2.2.4 on 2019-08-24 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0007_auto_20190824_0252"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="task_id",
        ),
    ]
