# Generated by Django 2.2.4 on 2019-08-12 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portal', '0001_initial'),
        ('users', '0002_profile_submission_folder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(blank=True)),
                ('rating', models.IntegerField(default=0)),
                ('is_selected', models.TextField(blank=True)),
                ('submission_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Submission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
            ],
        ),
    ]
