# Generated by Django 2.2.4 on 2019-09-03 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_auto_20190821_1515"),
        ("review", "0003_auto_20190813_1916"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.Profile",
                verbose_name="Reviewed By",
            ),
        ),
        migrations.CreateModel(
            name="SelectionResult",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.Profile"
                    ),
                ),
            ],
        ),
    ]
